services:
  - name: splittify-backend
    type: web
    env: node
    plan: free  # Cambia il piano se necessario
    buildCommand: |
      cd backend && npm install && npm run build
    startCommand: |
      cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb://splittify-mongo:27017/splittify
      - key: JWT_SECRET_KEY
        value: NotAVerySecureKey
    autoDeploy: true

  - name: splittify-mongo
    type: web
    env: docker
    plan: free  # Cambia il piano se necessario
    dockerfilePath: ./Dockerfile.mongo
    autoDeploy: true
