services:
  - name: splittify-backend
    type: web
    env: node
    plan: free  # Puoi cambiare il piano se necessario
    buildCommand: |
      cd backend && npm install && npm run build
    startCommand: |
      cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb://splittify-mongo:27017/splittify
      - key: JWT_SECRET_KEY
        value: NotAVerySecureKey
    mounts:
      - type: volume
        name: mongo-data
        path: /data/db
    regions: oregon  # Puoi cambiare la regione se necessario
    autoDeploy: true

  - name: splittify-mongo
    type: database
    plan: free  # Puoi cambiare il piano se necessario
    image: mongo:6
    command: mongod --bind_ip_all
    mounts:
      - type: volume
        name: mongo-data
        path: /data/db
    regions: oregon  # Puoi cambiare la regione se necessario
    autoDeploy: true

volumes:
  - name: mongo-data
