services:
  - name: splittify-backend
    type: web
    env: node
    plan: free  # Cambia il piano se necessario
    buildCommand: |
      cd backend && npm install && npm run build
    startCommand: |
      cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb://splittify-mongo:27017/splittify
      - key: JWT_SECRET_KEY
        value: NotAVerySecureKey
    autoDeploy: true
    regions: oregon  # Cambia la regione se necessario

  - name: splittify-mongo
    type: web
    plan: free  # Cambia il piano se necessario
    env: docker
    dockerfilePath: ./Dockerfile.mongo
    ports:
      - port: 27017
    mounts:
      - type: volume
        name: mongo-data
        path: /data/db
    autoDeploy: true
    regions: oregon  # Cambia la regione se necessario

volumes:
  - name: mongo-data
